### ISSUE TITLE
Register funktionalität Major

### ISSUE THREAD

**Issue by Burgomehl** [Burgomehl/SWE-III-SA#14]
Dabei darauf achten validatoren und konvertierer zu verwenden. Am besten eigene. Siehe semesteraufgabe.

**Comment by Burgomehl** [comment]
.

**Comment by GabrielInTheWorld** [comment]
added functionality to page register.xhtml - so registering is now possible.
Also added validators for email, password, birthday and converter for at least two names (except last name)
