### ISSUE TITLE
Warenkorb Blocker

### ISSUE THREAD

**Issue by Burgomehl** [Burgomehl/SWE-III-SA#2]
Füge eine Seite Warenkorb hinzu.
-> button auf jede Produktseite, der das jeweilige produkt in den warenkorb zieht
im Warenkorb
-> die Möglichkeit das Produkt auch wieder raus zu nehmen
-> kaufen -> Lieeradresse angeben ->  bezahlinformationen (jeweils eigene seite ) -> am ende kauf bestätigen

**Comment by AIIucard** [comment]
under construction

**Comment by AIIucard** [comment]
90% fertig

**Comment by Burgomehl** [comment]
Der weg zum abgeschlossenene Kauf fehlt hier noch

**Comment by Burgomehl** [comment]
soweit fertig
