### ISSUE TITLE
Einstellungen -> Daten erstellen

### ISSUE THREAD

**Issue by GabrielInTheWorld** [Burgomehl/SWE-III-SA#25]
Die Seite "Daten" unter Einstellungen hinzufügen - welche Funktionalität soll diese haben?
Bearbeitung der Userdaten?

**Comment by Burgomehl** [comment]
Die Seite existiert nichtmal

**Comment by Burgomehl** [comment]
Persönlich Kundendaten. So wie du es aus einem Webshop kennst. ach email hat sich geändert, kann man sie ändern. Passwort ändern etc

**Comment by Burgomehl** [comment]
fertig
