### ISSUE TITLE
ProduktSeite

### ISSUE THREAD

**Issue by Burgomehl** [Burgomehl/SWE-III-SA#32]
Ist ja schön weiß und so aber da fehlt mir was:

Knopf in den Warenkorb mit Anzahl!
Kommentarfunktion!?

Was passt da noch rein?

**Comment by Burgomehl** [comment]
Anzeige ähnlicher Produkte ?!?!?! SPrich Produkte die einen auch interessieren könnten

**Comment by GabrielInTheWorld** [comment]
Wollen wir das dann so umgestalten, dass die Startseite lediglich nach bestimmten Auswahlkriterien hervorgehobene Produkte anzeigt und nachdem ein Benutzer sich registriert hat, werden die Suchanfragen gespeichert und so ein weiteres Feld bei der Startseite mit ähnlichen Produkten angezeigt?

**Comment by Burgomehl** [comment]
Hatte jetzt eher gedacht auf der jeweiligen Produktseite mehr ein zu Pflegen die Seite ist doch arg karg

**Comment by Burgomehl** [comment]
#40 beshcreibt das letzte was auf der Siete noch fehlt
