### ISSUE TITLE
StartseiteAdmin

### ISSUE THREAD

**Issue by GabrielInTheWorld** [Burgomehl/SWE-III-SA#37]
Was soll eigentlich auf dieser Seite alles sein? :smile: 
Habe jetzt an Link zu der ProdukteAdmin.xhtml und Bearbeitung von Benutzern vielleicht noch gedacht... aber was noch?

**Comment by Burgomehl** [comment]
Link zu:
Produkte Anlegen
ProdukteAdmin
Kundenliste

vllt auch zu allen anderen "Normalen" Seiten (Menü oben raus nehmen)

**Comment by Burgomehl** [comment]
fertig
