### ISSUE TITLE
Productseite

### ISSUE THREAD

**Issue by Burgomehl** [Burgomehl/SWE-III-SA#40]
Auf der Produktseite (einzelne Produkte) soll ein ContentFlow integriert werden mit Produkten die einen auch interessieren könnten.

**Comment by Burgomehl** [comment]
Ist zwar nicht ganz ein contentFlow geworden, aber das ding ist auch gut. Jetzt fehlt nur noch das man diese angezeigten Produkte anklicken kann

**Comment by GabrielInTheWorld** [comment]
ContentFlow wurde es nicht, da bei mir nur ein schwarzer Balken mit dem Inhalt "Loading..." erscheint
