### ISSUE TITLE
Autocomplete --> trivial

### ISSUE THREAD

**Issue by GabrielInTheWorld** [Burgomehl/SWE-III-SA#41]
können wir machen, wenn wir am Ende noch etwas Zeit haben...

**Comment by GabrielInTheWorld** [comment]
Autocomplete ist algorithmisch betrachtet, glaub, richtiger Aufwand... Es sei denn es gibt dazu etwas gutes im Internet

**Comment by Burgomehl** [comment]
abgelehnt
